# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DispatchCli < Formula
  desc "Dispatch CLI"
  homepage "https://dispathc.run"
  version "0.1.0-alpha1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_darwin_amd64.tar.gz"
      sha256 "4fd296883dcd191100ba66a5a2b2e34c24a623fd6b15df5393e20e7999cf2f64"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_darwin_arm64.tar.gz"
      sha256 "bf37ef43fe3c2752341a690040e29883869e054d452d3bee72938b5386fc1393"

      def install
        bin.install "dispatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_linux_amd64.tar.gz"
      sha256 "a1f9d7d4edaa892cee0685d99a4fe02368e7d68143165a4fdb228a7a056f541f"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_linux_arm64.tar.gz"
      sha256 "2f3ea302bba18990b5e226339be4c5eda7ffb81a33e9c19a2557f10bb37cadf3"

      def install
        bin.install "dispatch"
      end
    end
  end

  conflicts_with "dispatch-cli"

  test do
    system "#{bin}/dispatch --version"
  end
end
