# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dispatch < Formula
  desc "Dispatch"
  homepage "https://dispatch.run"
  version "0.1.0-alpha1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch/releases/download/v0.1.0-alpha1/dispatch_0.1.0-alpha1_darwin_amd64.tar.gz"
      sha256 "9fda4301ea178d458ac6cce648be0018f6ea35b9299051dbcb2abdfdbe62ab86"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stealthrocket/dispatch/releases/download/v0.1.0-alpha1/dispatch_0.1.0-alpha1_darwin_arm64.tar.gz"
      sha256 "5aaa4e810a60788b4fb99fe65275c1d9c0f3401abd02a006e182c4a388d22bea"

      def install
        bin.install "dispatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch/releases/download/v0.1.0-alpha1/dispatch_0.1.0-alpha1_linux_amd64.tar.gz"
      sha256 "c9786cf51dccf6d624c404002479556a6d237f2bf7aac5b0c16a1fc42ce0d923"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stealthrocket/dispatch/releases/download/v0.1.0-alpha1/dispatch_0.1.0-alpha1_linux_arm64.tar.gz"
      sha256 "f643f4cb55d99ac13917841e2e55bea62e8525425f407e926c6ff5eed6b008ea"

      def install
        bin.install "dispatch"
      end
    end
  end

  test do
    system "#{bin}/dispatch --version"
  end
end
