# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dispatch < Formula
  desc "A platform for developing scalable & reliable distributed systems."
  homepage "https://dispatch.run"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.1.0/dispatch_0.1.0_darwin_amd64.tar.gz"
      sha256 "7c41ca087b9cd157c3530ba7ebe13ee58b49e4c69d0149789060f46a11b33235"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.1.0/dispatch_0.1.0_darwin_arm64.tar.gz"
      sha256 "a5f5f0b30c932fecade4c0598ff0a3b71cc282188ccc10f401f3ad1d7e398ed8"

      def install
        bin.install "dispatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.1.0/dispatch_0.1.0_linux_amd64.tar.gz"
      sha256 "fac505d9bbe03a9352db565c3585d459e3a6fe7dcde04b094fd488b5eaa4dda9"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.1.0/dispatch_0.1.0_linux_arm64.tar.gz"
      sha256 "d64668b59d30e6fd240c30f5b3384452988b575c79bc63856b17d5ae449051cd"

      def install
        bin.install "dispatch"
      end
    end
  end

  test do
    system "#{bin}/dispatch", "--version"
  end
end
