# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DispatchCli < Formula
  desc "Dispatch CLI"
  homepage "https://dispathc.run"
  version "0.1.0-alpha1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_darwin_amd64.tar.gz"
      sha256 "861cb92b72f755060e0803693e2b1b736ad1a580373e548bec70234eb487c65f"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_darwin_arm64.tar.gz"
      sha256 "2164e0f8cc3ac43a7d1eadfd3b9e17afd4856c9d7141cd30783dbece3be70287"

      def install
        bin.install "dispatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_linux_amd64.tar.gz"
      sha256 "72ae909676f9661e40f57eb20ee809cf50a9f6ffb1ef0fa6c9bd9491679dd13e"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stealthrocket/dispatch-cli/releases/download/v0.1.0-alpha1/dispatch-cli_0.1.0-alpha1_linux_arm64.tar.gz"
      sha256 "770f9c63aa4f4c0b4264ad29e0319e0de7824646672b853d5f6170603cb8c919"

      def install
        bin.install "dispatch"
      end
    end
  end

  conflicts_with "dispatch-cli"

  test do
    system "#{bin}/dispatch --version"
  end
end
