# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dispatch < Formula
  desc "A platform for developing scalable & reliable distributed systems."
  homepage "https://dispatch.run"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.2.0/dispatch_0.2.0_darwin_amd64.tar.gz"
      sha256 "924de08f763c160cc5080484b8c0380703cd475106428e83de79782d33c180aa"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.2.0/dispatch_0.2.0_darwin_arm64.tar.gz"
      sha256 "6f7645d6552705d5e9647c7d36988248e23f8d08adf7049e15ee965f0f35450a"

      def install
        bin.install "dispatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.2.0/dispatch_0.2.0_linux_amd64.tar.gz"
      sha256 "ba357607429dad60e93218a9318364c0041c3190e9f8863af6bd66f19f5335f6"

      def install
        bin.install "dispatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dispatchrun/dispatch/releases/download/v0.2.0/dispatch_0.2.0_linux_arm64.tar.gz"
      sha256 "28f1368328e49e57c64c2be46edd782b24f5aa0ce202e7768785a5783634d8bb"

      def install
        bin.install "dispatch"
      end
    end
  end

  test do
    system "#{bin}/dispatch", "--version"
  end
end
